### PR TITLE
Remove silly while that gets invalid values stuck in a loop + tests

### LINKED ISSUE #47: Providing a value of an incorrect type inside a composite makes codec enter an infinite loop
Minimal reproducible example:

```rust
use scale_info::{MetaType, PortableRegistry, Registry, TypeInfo};
use scale_value::{scale::encode_as_type, Value};

#[derive(TypeInfo)]
struct A(bool);

fn main() {
    let a = MetaType::new::<A>();
    let mut types = Registry::new();
    let id_a = types.register_type(&a);
    let types: PortableRegistry = types.into();

    let value = Value::unnamed_composite(vec![
        Value::from_bytes(0u32.to_le_bytes())
    ]);

    let mut bytes = Vec::new();
    encode_as_type(&value, id_a.id, &types, &mut bytes).unwrap();
}
```

Gets stuck in this loop forever:

https://github.com/paritytech/scale-value/blob/c5c35123cdcb1748371f1e06d0f339e185b9a523/src/scale_impls/encode.rs#L217-L223

### PR DESCRIPTION
**Pull request by jsdw**
Remove a while loop that was going to keep looping around forever if the inner value wasn't correct.

Add a test that the original bug is fixed, and a test to prove that we still handle "newtype wrapped values" regardless.

Closes #47

### CODE REVIEW

**Review by lexnv — APPROVED** [review]

File: src/scale_impls/encode.rs [hunk 1]
```diff
@@ -579,4 +598,48 @@ mod test {
...
+                Value::unnamed_composite(vec![Value::u128(32)]),
+            ])]),
+            Foo { inner: 32 },
+        );
+    }
+
+    // As of https://github.com/paritytech/scale-value/issues/47, this test will take
+    // too long and time out. Keep the test to ensure that things do finish as expected!
+    #[test]
+    fn encoding_shouldnt_take_forever() {
```
Comment (niklasad1) [inline src/scale_impls/encode.rs:631]: you could mark the test with `#[should_panic(expected = "some err")]` to make it more clear but good enough for me

**Review by niklasad1 — APPROVED** [review]

File: src/scale_impls/encode.rs (hunk 1 above)
Comment (jsdw) [reply src/scale_impls/encode.rs:631]: It's the opposite; it shouldn't panic unless it's failing :)

Comment (niklasad1) [reply src/scale_impls/encode.rs:631]: >  // As of https://github.com/paritytech/scale-value/issues/47, this test will take
> // too long and time out. Keep the test to ensure that things do finish as expected!

Then I'm not understanding this comment :point_up: :monocle_face:

Comment (niklasad1) [reply src/scale_impls/encode.rs:635]: ah make sense :)
